# Generated by Django 3.1.2 on 2020-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0004_auto_20201113_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='picture',
            field=models.CharField(default='none', max_length=120, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=120, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=120, verbose_name='Пользователь'),
        ),
    ]
