# Generated by Django 3.1.2 on 2020-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_auto_20201114_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(default='', max_length=120, verbose_name='Изображение'),
        ),
    ]
