# Generated by Django 3.1.2 on 2020-11-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0006_auto_20201114_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(default='none', max_length=120, verbose_name='Изображение'),
        ),
    ]
