# Generated by Django 3.1.2 on 2020-11-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0008_auto_20201114_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(max_length=300, verbose_name='Изображение'),
        ),
    ]
