# Generated by Django 3.1.2 on 2020-11-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0009_auto_20201115_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(default='none', max_length=300, verbose_name='Изображение'),
        ),
    ]
