# Generated by Django 3.1.2 on 2020-11-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0012_auto_20201115_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Изображение'),
        ),
    ]
