# Generated by Django 3.1.2 on 2020-11-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0013_auto_20201115_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст'),
        ),
    ]
