# Generated by Django 3.1.2 on 2020-11-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0014_auto_20201117_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Текст'),
        ),
    ]
