# Generated by Django 3.1.2 on 2020-11-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0015_auto_20201117_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='card_bg',
            field=models.CharField(default='bg-dark', max_length=100, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='message',
            name='card_clr',
            field=models.CharField(default='white', max_length=100, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Изображение'),
        ),
    ]
