# Generated by Django 3.1.2 on 2020-11-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0020_auto_20201118_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='card_bg_color_choice',
            new_name='choicebg',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='card_font_color_choice',
            new_name='choiceclr',
        ),
    ]
