# Generated by Django 3.1.2 on 2020-11-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0021_auto_20201118_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='choicebg',
            new_name='card_bg_color_choice',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='choiceclr',
            new_name='card_font_color_choice',
        ),
    ]
