# Generated by Django 3.1.2 on 2020-11-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0022_auto_20201118_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='card_bg_color_choice',
            field=models.CharField(choices=[('Темный фон', 'bg-dark'), ('Светлый фон', 'bg-light'), ('Синий фон', 'bg-primary'), ('Серый фон', 'bg-secondary'), ('bg-success', 'bg-success'), ('bg-danger', 'bg-danger'), ('bg-warning', 'bg-warning'), ('bg-info', 'bg-info')], default='bg-dark', max_length=100, verbose_name='Текст'),
        ),
    ]
