# Generated by Django 3.1.2 on 2020-11-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0024_auto_20201121_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=10000, verbose_name='Текст'),
        ),
    ]
