# Generated by Django 3.1.2 on 2020-11-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0025_auto_20201125_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='card_font_color_choice',
            field=models.CharField(choices=[('text-white', 'Белый текст'), ('text-dark', 'Темный текст'), ('text-primary', 'Синий текст'), ('text-secondary', 'Серый текст'), ('text-warning', 'Желтый текст'), ('text-danger', 'Красный текст'), ('text-success', 'Зеленый цвет'), ('text-info', 'Голубой цвет')], default='text-white', max_length=100, verbose_name='Текст'),
        ),
    ]
