# Generated by Django 3.1.2 on 2020-11-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0026_auto_20201128_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='top',
            field=models.CharField(choices=[('False', 'Не закреплена'), ('True', 'Закрепить'), ('None', 'Скрытая')], default='False', max_length=100, null=True, verbose_name='Закрепить'),
        ),
    ]
