# Generated by Django 3.1.2 on 2020-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0027_auto_20201128_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='picture_file',
            field=models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Загрузка пикчи'),
        ),
    ]
