# Generated by Django 3.1.2 on 2020-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0028_message_picture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture_file',
            field=models.ImageField(max_length=200, null=True, upload_to='media', verbose_name='Загрузка пикчи'),
        ),
    ]
