# Generated by Django 3.1.2 on 2020-12-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0033_auto_20201203_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture_file',
            field=models.FileField(max_length=200, null=True, upload_to='msg', verbose_name='Загрузка пикчи'),
        ),
    ]
