# Generated by Django 3.1.2 on 2020-12-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0035_auto_20201203_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.CharField(blank=True, default='none', max_length=100, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='picture_file',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='msg', verbose_name='Загрузка пикчи'),
        ),
        migrations.AlterField(
            model_name='message',
            name='top',
            field=models.CharField(blank=True, choices=[('False', 'Не закреплена'), ('True', 'Закрепить'), ('None', 'Скрытая')], default='False', max_length=100, null=True, verbose_name='Закрепить'),
        ),
    ]
