# Generated by Django 3.1.2 on 2020-12-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0036_auto_20201203_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='picture_file',
            field=models.ImageField(blank=True, default='none', max_length=200, upload_to='msg', verbose_name='Загрузка пикчи'),
        ),
    ]
