# Generated by Django 3.1.2 on 2020-12-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0037_auto_20201203_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='card_bg_color_choice',
            field=models.CharField(choices=[('bg-dark', 'Темный фон'), ('bg-light', 'Светлый фон'), ('bg-primary', 'Синий фон'), ('bg-success', 'Зеленый фон'), ('bg-danger', 'Красный фон'), ('bg-warning', 'Желтый фон'), ('bg-info', 'Голубой фон')], default='bg-dark', max_length=100, verbose_name='Текст'),
        ),
    ]
