# Generated by Django 3.1.2 on 2020-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0038_auto_20201205_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='admin_news',
            field=models.BooleanField(default='False', verbose_name='Новости сайта'),
        ),
    ]
