# Generated by Django 3.1.2 on 2020-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0039_message_admin_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='card_bg_color_choice',
            field=models.CharField(choices=[('bg-dark', 'Темный фон'), ('bg-light', 'Светлый фон'), ('bg-primary', 'Синий фон'), ('bg-success', 'Зеленый фон'), ('bg-danger', 'Красный фон'), ('bg-warning', 'Желтый фон'), ('bg-info', 'Голубой фон')], default='bg-dark', max_length=100, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='message',
            name='card_font_color_choice',
            field=models.CharField(choices=[('text-white', 'Белый текст'), ('text-dark', 'Темный текст'), ('text-primary', 'Синий текст'), ('text-secondary', 'Серый текст'), ('text-warning', 'Желтый текст'), ('text-danger', 'Красный текст'), ('text-success', 'Зеленый цвет'), ('text-info', 'Голубой цвет')], default='text-white', max_length=100, verbose_name='Цвет текста'),
        ),
    ]
