# Generated by Django 3.1.2 on 2021-01-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0042_privat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privat',
            options={'verbose_name': 'Приватное', 'verbose_name_plural': 'Приватные сообщения'},
        ),
    ]
